include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    avoid_print: false 
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
