name: Run tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.5'
        channel: "stable"

    - name: Build
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Test
      run: flutter test